import type { Asset } from "./types";

/** HARLF 14-asset book (Coriat & Benhamou, arXiv:2507.18560). */
export const ASSETS: Asset[] = [
  {
    id: "GSPC",
    ticker: "^GSPC",
    name: "S&P 500",
    region: "United States",
    desk: "Markets",
    assetClass: "Equities",
    keywords: ["S&P 500", "SPX", "Wall Street"],
  },
  {
    id: "IXIC",
    ticker: "^IXIC",
    name: "NASDAQ Composite",
    region: "United States",
    desk: "Technology",
    assetClass: "Equities",
    keywords: ["Nasdaq", "semiconductors", "Magnificent Seven"],
  },
  {
    id: "DJI",
    ticker: "^DJI",
    name: "Dow Jones Industrial Average",
    region: "United States",
    desk: "Industrials",
    assetClass: "Equities",
    keywords: ["Dow", "industrials"],
  },
  {
    id: "FCHI",
    ticker: "^FCHI",
    name: "CAC 40",
    region: "France",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["CAC 40", "Paris", "France"],
  },
  {
    id: "FTSE",
    ticker: "^FTSE",
    name: "FTSE 100",
    region: "United Kingdom",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["FTSE", "London", "UK gilt"],
  },
  {
    id: "SX5E",
    ticker: "^STOXX50E",
    name: "Euro Stoxx 50",
    region: "Euro area",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["Euro Stoxx", "ECB", "eurozone"],
  },
  {
    id: "HSI",
    ticker: "^HSI",
    name: "Hang Seng",
    region: "Hong Kong",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["Hang Seng", "Hong Kong", "China property"],
  },
  {
    id: "SSEC",
    ticker: "000001.SS",
    name: "Shanghai Composite",
    region: "China",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["Shanghai", "PBOC", "China"],
  },
  {
    id: "BSESN",
    ticker: "^BSESN",
    name: "BSE Sensex",
    region: "India",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["Sensex", "Mumbai", "RBI"],
  },
  {
    id: "NSEI",
    ticker: "^NSEI",
    name: "Nifty 50",
    region: "India",
    desk: "Equities",
    assetClass: "Equities",
    keywords: ["Nifty", "India", "FIIs"],
  },
  {
    id: "KS11",
    ticker: "^KS11",
    name: "KOSPI",
    region: "South Korea",
    desk: "Technology",
    assetClass: "Equities",
    keywords: ["KOSPI", "Samsung", "HBM"],
  },
  {
    id: "GC",
    ticker: "GC=F",
    name: "Gold",
    region: "Global",
    desk: "Commodities",
    assetClass: "Commodities",
    keywords: ["gold", "bullion", "XAU"],
  },
  {
    id: "SI",
    ticker: "SI=F",
    name: "Silver",
    region: "Global",
    desk: "Commodities",
    assetClass: "Commodities",
    keywords: ["silver", "XAG"],
  },
  {
    id: "CL",
    ticker: "CL=F",
    name: "WTI crude",
    region: "Global",
    desk: "Energy",
    assetClass: "Commodities",
    keywords: ["oil", "WTI", "OPEC"],
  },
];

export const ASSET_IDS = ASSETS.map((a) => a.id);

export const ASSET_BY_ID = Object.fromEntries(ASSETS.map((a) => [a.id, a]));

export const EQUAL_WEIGHT = 1 / ASSETS.length;

export const SAMPLE_MONTHS = [
  "2024-01",
  "2024-02",
  "2024-03",
  "2024-04",
  "2024-05",
  "2024-06",
  "2024-07",
  "2024-08",
  "2024-09",
  "2024-10",
  "2024-11",
  "2024-12",
  "2025-01",
  "2025-02",
  "2025-03",
  "2025-04",
  "2025-05",
  "2025-06",
  "2025-07",
  "2025-08",
  "2025-09",
  "2025-10",
  "2025-11",
  "2025-12",
] as const;

export type SampleMonth = (typeof SAMPLE_MONTHS)[number];
